# Generated by Django 4.2.30 on 2026-04-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0002_entry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
